version: '3.8'

services:
  server:
    image: server
    restart: unless-stopped
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./src:/app/src     
    networks:
      - my-bridge
    env_file:
      - .env
  postgres:
    image: postgres-db
    restart: unless-stopped
    build: ./DB/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-bridge
    env_file:
      - .env


networks:
   my-bridge:
    driver: bridge
volumes:
  pgdata:
  logs: