version: '3.8'

services:
  server:
    image: server
    restart: unless-stopped
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT = ${PORT}
    volumes:
      - logs:/usr/src/app/logs
    networks:
      - my-bridge
    env_file:
      - .env
  postgres:
    image: postgres-db
    restart: unless-stopped
    build: ./DB/
    ports:
      - ${PGPORT}:${PGPORT}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRESS_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-bridge
    env_file:
      - .env


networks:
   my-bridge:
volumes:
  pgdata:
  logs: